name: Hourly Bellhop Data Collection

on:
  # Run immediately when committed to repository
  push:
    branches: [ main ]
  
  # Run hourly
  schedule:
    - cron: '0 * * * *'  # Run at the top of every hour

jobs:
  collect-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-cloud-storage requests

    - name: Setup Google Cloud Auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    
    - name: Run data collection script
      env:
        BELLHOP_API_KEY: ${{ secrets.BELLHOP_API_KEY }}
        BELLHOP_API_SECRET: ${{ secrets.BELLHOP_API_SECRET }}
        GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
      run: python bellhop_gcs_script.py